

spring:
  application:
    name: avclient



server:
  port: 9091


management:
  metrics:
    web:
      server:
        request:
          autotime:
            enable: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
  health:
    show-details: always

realRequest: false